accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    # path('login/', views.login_view, name='login'),
    # path('logout/', auth_views.LogoutView.as_view(next_page='shop:allProdCat'), name='logout'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),

]

cart/urls.py
from django.urls import path

from cart import views
app_name = 'cart'
urlpatterns = [
    path('',views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/',views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove, name='full_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
# from ecommerce import settings
from django.conf import settings

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('search_app/', include('search_app.urls')),
    path('', include('shop.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views
app_name='search_app'
urlpatterns = [
    path('',views.searchResult, name='searchResult'),
]

shop/urls.py
from django.urls import path
from . import views
app_name='shop'
urlpatterns = [
    # path('', views.demo, name='demo'),
    path('', views.allProdCat, name='allProdCat'),
     path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('add/', views.add, name='add'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='proDetail'),
]

cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        discounted_price = self.product.get_final_price()
        return discounted_price * self.quantity

    def __str__(self):
        return str(self.product)

cart/views.py
from django.shortcuts import get_object_or_404, render, redirect

from shop.models import Product
from .models import Cart, CartItem
# Create your views here.
# def fun(request):
#     return render(request, 'product.html')
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def migrate_cart_session_to_user(request):
    session_cart_id = _cart_id(request)
    if request.user.is_authenticated:
        try:
           session_cart = Cart.objects.get(cart_id=session_cart_id)
           user_cart, created = Cart.objects.get_or_create(user=request.user)
           for item in CartItem.objects.filter(cart = session_cart):
               item.cart = user_cart
               item.save()
           session_cart.delete()
        except Cart.DoesNotExist:
            pass 

def add_cart(request, product_id):
    
    product = Product.objects.get(id = product_id)
    try:
        if request.user.is_authenticated:
            cart, created = Cart.objects.get_or_create(user=request.user)
        else:
            cart, created = Cart.objects.get_or_create(cart_id=_cart_id(request))

        # cart = Cart.objects.get(cart_id = _cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
    cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            quantity = 1,
            cart = cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        if request.user.is_authenticated:
            cart, created = Cart.objects.get_or_create(user=request.user)
        else:
            cart, created = Cart.objects.get_or_create(cart_id=_cart_id(request))
        # cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            # total += (cart_item.product.price * cart_item.quantity)
            total += (cart_item.product.get_final_price() * cart_item.quantity)
            counter += cart_item.quantity
    except Cart.ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))

def cart_remove(request, product_id):
    if request.user.is_authenticated:
            cart, created = Cart.objects.get_or_create(user=request.user)
    else:
            cart, created = Cart.objects.get_or_create(cart_id=_cart_id(request))

    # cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request, product_id):
    if request.user.is_authenticated:
            cart, created = Cart.objects.get_or_create(user=request.user)
    else:
            cart, created = Cart.objects.get_or_create(cart_id=_cart_id(request))

    # cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}  {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css">
</head>
<body>
    <!-- <div class="container"> -->
        <div>
        {% include 'header.html' %}
        
        {% include 'navbar.html' %}
        {% if user.is_authenticated %}
            Welcome, {{user.username}} | <a href="{% url 'accounts:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'accounts:login' %}">Login</a>
            <a href="{% url 'accounts:register' %}">Register</a>
        {% endif %}
        {% block content %}
        {% endblock %}
        </div>
        {% include 'footer.html' %}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" ></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.min.js" ></script>
    
    
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %} 
    This is the cart page. Proceed to review your items and place the order.
{% endblock %}

{% block title %} 
    Cart - Online Store Easy Solutions
{% endblock %}

{% block content %}
    {% if not cart_items %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my-title">
                Your Shopping cart is Empty!
            </h1>
            <br>
            <p class="text-center"> 
                Please Click <a href="{% url 'shop:allProdCat' %}">Here</a> to continue shooping
            </p>
        </div>
    </div>
    {% else %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">
                Your Shopping Cart
            </h1>
            <br>

        </div>

        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th colspan="5">
                                Your Items
                            </th>
                        </tr>

                    </thead>
                    <tbody>
                        
                        {% for cart_item in cart_items %}
                        <tr>
                            <td>
                                <a href="cart_item.product.get_absolute_url">
                                    <img src="{{cart_item.product.image.url}}" alt="" style="width: 100px; height: 100px;" class="float-left rounded costom_image">
                                </a>
                            </td>
                            <td class="text-left">
                                Name: {{cart_item.product.name}}
                                <br>
                                ID: {{cart_item.product.id}}
                                <br>
                                <!-- Price: ${{cart_item.product.price}} -->
                                 {% if cart_item.product.get_discount_percentage > 0 %}
                        <strong><p style="color: crimson;">Discount: {{cart_item.product.get_discount_percentage}}%</p></strong>

                                 Price: $ <strike>{{cart_item.product.price}}</strike> {{cart_item.product.get_final_price}}
                                {% else %}
                                    Price: ${{cart_item.product.price}}
                                    {% endif %}
                                <br>
                                Quantity: {{cart_item.quantity}} X ${{cart_item.product.get_final_price}}

                            </td>
                            <td>
                                ${{cart_item.sub_total}}
                            </td>
                            {% if cart_item.quantity < cart_item.product.stock %}
                            <td>
                                <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_icon">
                                    <i class="fa-solid fa-plus custom_icon"></i>
                                </a> 
                
                            </td>
                                                        <td>
                                <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon">
                                    <i class="fa-solid fa-minus"></i>
                                    <!-- <i class="fa-regular fa-square-minus"></i> -->
                                </a> 
                            </td>
                            <td>
                                <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon">
                                    <i class="fa-solid fa-trash"></i></a>
                                &nbsp;
                            </td>
                            {% else %}
                            <td>
                                <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon">
                                    <i class="fa-solid fa-minus"></i>
                                    <!-- <i class="fa-regular fa-square-minus"></i> -->
                                </a> 
                            </td>
                            <td>
                                <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon">
                                    <i class="fa-solid fa-trash"></i></a>
                                &nbsp;
                            </td>    
                            {% endif %}
                        </tr>
                        {% endfor %}
                        <!-- <tr class="d-flex flex-column me-3"> -->
                            <tr class="me-3">
                            <td class="text-left">
                                Your total is : <strong>{{total}}</strong>
                            </td>
                        </tr>
                
                    </tbody>
                </table>
                {% endif %}
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table my_custom_table">
                        <thead class="my_custom_thead">
                            <tr>
                                <th>
                                    Checkout
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    Please review your shopping cart items before proceeding with the order payment.
                                </td>
                            </tr>
                        </tbody>

                    </table>
                    <div class="mx-auto">
                        <a class="btn btn-secondary btn-block my_custom_button" href="{% url 'shop:allProdCat' %}">Continue Shopping</a>
                        <br><br>
                    </div>
                </div>
          </div>  
        </div>
    </div>
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %} 
    {% if category %}
    {{ category.description|truncatewords:155}}
    {% else %}
    Welcome to Fadel & Spies where you can buy all kinds of products
    {% endif %}
{% endblock %}

{% block title %} 
    {% if category %}
    {{ category.name }} - Fadel & Spies
    {% else %}
    See our New Collections - Fadel & Spies
    {% endif %}
{% endblock %}

{% block content %}
{% if category %}
<div>
    <div class="row my_row_class">
        <div class="mx-auto">
        <p><a href="{% url 'shop:allProdCat' %}">Our Collections</a></p>
        </div>
    </div>
</div>
{% endif %}
<div class="mx-auto">
    {% if category %}
    <center>
    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" height="450px" width="1600px">
    </center>
</div>
<br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
{% else %}
<div>
    <img class="my_image my_image_padding" src="{% static 'img/banner.png'%}" alt="our products" height="450px" width="1600px">
</div>
<br>
<div>
    <h1 class="text-center my_title">Our Quality Products Collections</h1>
    <p class="text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

</div>
{% endif %}

<div class="container">
    <div class="row">
        {% for product in products.object_list %}
        <div class="col-md-4 mb-4">
            <div class="card h-100 text-center" style="min-width: 18 rem;">
                <br><br>
                <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    {% if product.get_discount_percentage > 0 %}
                        <strong><p style="color: crimson;">Discount: {{product.get_discount_percentage}}%</p></strong>
                        <p><strong>Price: $ <strike>{{product.price}}</strike> {{product.get_final_price}}</strong></p>
                    {% else %}
                        <p><strong>Price: ${{product.price}}</strong></p>
                    {% endif %}
                </div>
                
            </div>
            <!-- <br> -->
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}

        </div>
        {% endif %}

    </div>
    <br>
</div>
{% endblock %}

templates/footer.html
<div class="footer navbar-fixed-bottom myfooter">
    <p class="text-center">&copy; Fadel & Spies Pvt Ltd. All rights Reserved </p>
</div>

templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shop:allProdCat' %}"><img src="{% static 'img/logo1.png' %}" alt="logo_image" height="130px" width="130px"><br>
        </a>
    </center>
</header>

templates/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{% block metadescription %} This is the home page of the ecommerce website {% endblock %}
{% block content %}
<div class="container">
    <div class="row">

<div class="form-group">
<div class="col-md-3">
<form action="add/" method="post" class="mb-3 shadow">
    {% csrf_token %}
    <h4> This is the home page </h4>
    Number 1: <input class="form-control" type="text" name="num1"><br>
    Number 2: <input class="form-control" type="text" name="num2"><br>
    <input type="submit" class="btn btn-success">
</form>
</div>
</div>
</div>
Result: {{ result }}
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<h2>Login</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>

{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <!-- <a class="navbar-brand" href="#">Navbar</a> -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!-- <li class="nav-item"> -->
          <!-- <a class="nav-link active" aria-current="page" href="#">Home</a> -->
        <!-- </li> -->
        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Shop</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:allProdCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}"></li>
            <!-- <li><a class="dropdown-item" href="#">Action</a></li> -->
            <!-- <li><a class="dropdown-item" href="#">Another action</a></li> -->
            <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a></li>
            <!-- <li><hr class="dropdown-divider"></li> -->
            <!-- <li><a class="dropdown-item" href="#">Something else here</a></li> -->
            {% for cat in links %}
        <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
        {% endfor %}
          </ul>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li> -->
       
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>{% if counter > 0 %}
          ({{counter}})
        {% endif %}</a>
        
        </li>
        
      </ul>
      <form class="d-flex" role="search"  action="{% url 'search_app:searchResult' %}" method="get">
        
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">
          <i class="fa-solid fa-magnifying-glass"></i>
        </button>
      </form>
    </div>
  </div>
</nav>
<!-- <nav>
    <ul>
        <li><a href="{% url 'shop:allProdCat' %}">All Products</a></li>
        {% for cat in links %}
        <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>
        {% endfor %}
        <li>Your Cart()</li>
    </ul>
</nav> -->

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{{product.description|truncatewords:155}}
{% endblock %}
{% block title %}
    {% if category %}
        {{product.name}} - Fadel&Spies
    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div mx-auto>
        <p><a href="{% url 'shop:allProdCat'%}">Home</a>
        <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
<div class="col-12 col-sm-12 col-md-12 col-lg-6">
    <div style="min-width: 18 rem;">
        <img src="{{product.image.url}}" alt="{{product.name}}">
    </div>
</div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6">
    <div>
        <div>
        <h1 class="my_product_title">{{product.name}}</h1>
        
        {% if product.get_discount_percentage > 0 %}
            <p style="color: crimson;">Discount: {{product.get_discount_percentage}}%</p>
            <p><strong>Price: $ <strike>{{product.price}}</strike> {{product.get_final_price}}</strong></p>
        {% else %}
                <p><strong>Price: ${{product.price}}</strong></p>
        {% endif %}
        <p class="text-justify my_prod_text">Product Description:</p>
        <p class="text-justify my_prod_text">{{product.description}}</p>
        {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
        {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
            
        {% endif %}

    </div>
</div>
</div>
</div>
</div>
<br><br>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}

<h1>Hello {{ user.username }}!
</h1>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Register{% endblock %}
{% block content %}
<h2>Register</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %} 
    We have variety of products.
{% endblock %}

{% block title %} 
    Search 
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for: <b>{{query}}</b></p>
</div>
<div class="container">
    <div class="row">
        {% for product in products %}
        <div class="col-md-4 mb-4">
            <div class="card h-100 text-center" style="min-width: 18 rem;">
                <br><br>
                <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
                
            </div>
            <!-- <br> -->
        </div>
        
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found</p>
        </div>

        {% endfor %}
    </div>
</div>

{% endblock %}